version: '2'

services:

  nginx:
    container_name: nginx-dev
    build: ./nginx
    restart: always
    ports:
      - 9081:80
    links:
      - nodejs
      
  nodejs:
    container_name: nodejs-dev
    build: .
    restart: always
    command: pm2-docker dbpool.pm2.json
    ports:
      - 4000
    volumes:
      - ./:/node
    environment:
      - NODE_ENV=development
      - NODE_PATH=src
